services:
  - type: web
    name: gbemisola-movies
    env: node
    buildCommand: "npm run install-all && npm run build"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
